name: main
on: push

jobs:
  tests:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v3
        
      - name: install
        run: make setup 
        
      - name: lint
        run: make lint
      
      - name: test
        run: make test
    
